services:
    qgis:
      image: qgis/qgis:3.44
      command: ["/bin/bash", "-c", "pip install debugpy; qgis /root/shogun_qgis_konfigurator.qgs"]
      environment:
        DISPLAY: "unix${DISPLAY}"
        RUN_IN_DOCKER: "1"
      ports:
        - "5678:5678"
      volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ./qgis_plugins:/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins
        - ../qgis-shogun-editor:/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-shogun-editor
