# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ShogunQgisConfigurator
                                 A QGIS plugin
 GeoPortal.rlp metadata search module
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-02-09
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Armin Retterath
        email                : armin.retterath@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os.path

from qgis.core import (
    Qgis,
    QgsBrowserModel,
    QgsMessageLog,
    QgsNetworkAccessManager,
    QgsProject,
    QgsProviderRegistry,
    QgsRasterLayer,
    QgsSettings,
)
from qgis.gui import QgsGui, QgsMessageBar, QgsMessageViewer

# some things for doing http requests
from qgis.PyQt.QtCore import QCoreApplication, QEventLoop, QSettings, Qt, QTranslator, QUrl, QUrlQuery
from qgis.PyQt.QtGui import QDesktopServices, QIcon, QPixmap
from qgis.PyQt.QtNetwork import QNetworkRequest
from qgis.PyQt.QtWidgets import QAction, QMessageBox

from .gui.editor import Editor

# Import the code for the dialog
from .qgis_shogun_editor_dialog import QgisShogunEditorDialog

# Initialize Qt resources from file resources.py


class QgisShogunEditor:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value("locale/userLocale")[0:2]
        locale_path = os.path.join(
            self.plugin_dir, "i18n", "gprlp_metadata_search_{}.qm".format(locale)
        )

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr("&Qgis Shogun Editor")

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        # self.first_start = None

        # read all settings from qgis settings
        self.settings = QgsSettings()

        # read actual browser model
        self.browser_model = QgsBrowserModel()

        # network access
        self.na_manager = QgsNetworkAccessManager.instance()

        self.disable_ssl_verification = self.settings.value(
            "/MetaSearch/disableSSL", False, bool
        )
        self.pluginIsActive = False
        self.editor = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate("QgisShogunEditor", message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToWebMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        icon_path = os.path.join(os.path.dirname(__file__), "shogun_logo.png")
        self.add_action(
            icon_path,
            text=self.tr("Qgis Shogun Editor"),
            callback=self.openEditor,  # ehemalig: self.run
            parent=self.iface.mainWindow(),
        )

        # will be set False in run()
        # self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginWebMenu(self.tr("Qgis Shogun Editor"), action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start:
            self.first_start = False
            self.dlg = QgisShogunEditorDialog()
            # search_catalogues
            # important - events should only be added once - otherwise we will go into trouble!
            self.dlg.pushButton.clicked.connect(lambda: self.start_search())
            # add logo
            logo_path = os.path.join(os.path.dirname(__file__), "shogun_logo.png")
            if logo_path:
                # build
                pixmap = QPixmap(logo_path)
                # draw preview
                self.dlg.labelLogo.setPixmap(
                    pixmap.scaled(
                        self.dlg.labelLogo.size(),
                        Qt.KeepAspectRatio,
                        Qt.SmoothTransformation,
                    )
                )
                self.dlg.labelLogo.mousePressEvent = self.open_project_link
            else:
                QgsMessageLog.logMessage(
                    "An error occured while try to open url: ",
                    "GeoPortal.rlp search",
                    level=Qgis.Critical,
                )
            # add link to github for help
            # help_icon_path = os.path.join(os.path.dirname(__file__), "questionmark.png")
            # self.dlg.labelHelp.setOpenExternalLinks(True)
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    def open_project_link(self, event):
        if event.button() == Qt.LeftButton:
            QDesktopServices.openUrl(QUrl("https://www.terrestris.de/de/"))

    def onClosePlugin(self):
        if self.editor is None:
            return
        connections_nr = self.editor.topitem.childCount()
        for x in range(connections_nr):
            try:
                connection = self.editor.topitem.child(x)
                connection.disconnectSignals()
            except Exception as e:
                print('could not disconnect signals for connection' + str(e))

    def openEditor(self):
        if not self.pluginIsActive:
            self.pluginIsActive = True

            self.editor = Editor(self.iface)
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.editor.dock)
            self.editor.dock.show()

        else:
            self.editor.dock.show()
