[metadata]
description_file = README.md

# -- Code quality ------------------------------------
[flake8]
count = True
exclude = venv,env,__pycache__,build,dist,.git,.eggs,*.egg-info,site-packages
ignore = T201, W503, W504, C901
max-complexity = 20
max-doc-length = 130
max-line-length = 120
per-file-ignores =
    __init__.py: E501, W505
    plugin_upload.py: E501, W505, F821
    resources.py: E501, W505
per-file-line_length = 21

[isort]
ensure_newline_before_comments = True
force_grid_wrap = 0
include_trailing_comma = True
line_length = 120
multi_line_output = 3
profile = black
use_parentheses = True

[pep8]
exclude = venv,env,__pycache__,build,dist,.git,.eggs,*.egg-info,site-packages
max-line-length = 120
