# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QgisShogunEditor
                                 A QGIS plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09
        copyright            : (C) 202 by terrestris
        email                : info@terrestris.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

from qgis.core import QgsMessageLog


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ShogunQgisConfigurator class from file ShogunQgisConfigurator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    import os
    from .plugin_utils.installer import ensure_venv, SHOGUN_VENV_NAME, ensure_dependencies

    project_path = os.path.dirname(__file__)
    QgsMessageLog.logMessage(f"Project path: {project_path}", "QgisShogunEditor")

    venv_path = ensure_venv(
        os.path.join(
            project_path,
            SHOGUN_VENV_NAME
        )
    )
    ensure_dependencies(venv_path)

    from .qgis_shogun_editor import QgisShogunEditor
    return QgisShogunEditor(iface)
