# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QgisShogunEditor
                                 A QGIS plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-09
        git sha              : $Format:%H$
        copyright            : (C) 2025 by terrestris
        email                : info@terrestris.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import json
import os.path

from qgis.core import (
    Qgis,
    QgsBrowserModel,
    QgsMessageLog,
    QgsNetworkAccessManager,
    QgsSettings,
)

# some things for doing http requests
from qgis.PyQt.QtCore import QCoreApplication, QEventLoop, QSettings, Qt, QTranslator, QUrl
from qgis.PyQt.QtGui import QDesktopServices, QIcon, QPixmap
from qgis.PyQt.QtNetwork import QNetworkRequest, QSslSocket
from qgis.PyQt.QtWidgets import QAction

# Import the code for the dialog
from .qgis_shogun_editor_dialog import QgisShogunEditorDialog

# Initialize Qt resources from file resources.py


class QgisShogunEditor:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # TODO initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'qgis_shogun_editor{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Shogun Qgis Configurator')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        # self.first_start = None

        # read all settings from qgis settings
        self.settings = QgsSettings()

        # read actual browser model
        self.browser_model = QgsBrowserModel()

        # network access
        self.na_manager = QgsNetworkAccessManager.instance()
        self.request = QNetworkRequest()

        # Achtung: T/F bei Zertifikaten
        self.disable_ssl_verification = self.settings.value(
            "/MetaSearch/disableSSL",
            True,
            bool
        )

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ShogunQgisConfigurator', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToWebMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        icon_path = os.path.join(os.path.dirname(__file__), "shogun_logo.png")
        self.add_action(
            icon_path,
            text=self.tr(u'Shogun Qgis Configurator'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginWebMenu(
                self.tr(u'Shogun Qgis Configurator'),
                action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start:
            self.first_start = False
            self.dlg = QgisShogunEditorDialog()

            self.dlg.entryUrl.setPlaceholderText('Please enter an URL')

            self.dlg.loadButton.clicked.connect(lambda: self.load_applications())

            # add logo
            logo_path = os.path.join(os.path.dirname(__file__), "shogun_logo.png")
            if logo_path:
                # build
                pixmap = QPixmap(logo_path)
                # draw preview
                self.dlg.labelLogo.setPixmap(pixmap.scaled(self.dlg.labelLogo.size(),
                                             Qt.KeepAspectRatio, Qt.SmoothTransformation))
                self.dlg.labelLogo.mousePressEvent = self.open_project_link
            else:
                QgsMessageLog.logMessage("An error occured while try to open url: ", 'QgisShogunEditor',
                                         level=Qgis.Critical)
            # add link to github for help
            # help_icon_path = os.path.join(os.path.dirname(__file__), "questionmark.png")
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    def open_project_link(self, event):
        if event.button() == Qt.LeftButton:
            QDesktopServices.openUrl(QUrl("https://www.terrestris.de/de/"))

    def check_url_for_applications(self, input_url):
        # check url and prepare for applications request
        # TODO: check for http and /
        input_url = str(input_url)
        if len(input_url) == 0:
            print('Please enter a valid url.')
            return
        else:
            if input_url.endswith('applications'):
                return input_url
            elif input_url.endswith('application'):
                return input_url + 's'
            elif input_url.endswith('/'):
                return input_url + 'applications'

    def check_url_for_layers(self, input_url):
        # check url and prepare for layers request
        # TODO: check for http and /
        input_url = str(input_url)
        if len(input_url) == 0:
            print('Please enter a valid url.')
            return
        else:
            if input_url.endswith('layers'):
                return input_url
            elif input_url.endswith('layer'):
                return input_url + 's'
            elif input_url.endswith('/'):
                return input_url + 'layers'

    def request_public_entity(self, url):
        self.request.setUrl(QUrl(url))

        # no certificate
        ssl_config = self.request.sslConfiguration()
        ssl_config.setPeerVerifyMode(QSslSocket.VerifyNone)
        self.request.setSslConfiguration(ssl_config)

        # request public application
        self.reply = self.na_manager.get(self.request)
        eventLoop = QEventLoop()
        self.reply.finished.connect(eventLoop.quit)
        eventLoop.exec_()  # blocs until finished

        if self.reply.error() == self.reply.NoError:
            self.response = self.reply.readAll().data().decode("utf-8")
            # print("Response:", self.response)
        else:
            self.response = None
            print("Error:", self.reply.errorString())
        self.reply.deleteLater()

        return self.response

    def find_all_layer_ids(self, layer_tree_json):
        layer_ids = []

        if "layerId" in layer_tree_json:
            print('Found layerId', layer_tree_json["layerId"])
            layer_ids.append(layer_tree_json["layerId"])

        if "children" in layer_tree_json:
            for child in layer_tree_json["children"]:
                layer_ids.extend(self.find_all_layer_ids(child))

        return layer_ids

    def load_applications(self):
        inputUrl = self.dlg.entryUrl.text()
        # check url
        applications_url = self.check_url_for_applications(inputUrl)
        layers_url = self.check_url_for_layers(inputUrl)
        if (len(applications_url) > 0 and len(layers_url) > 0):
            # request (all public) applications
            applications_response = self.request_public_entity(applications_url)
            applications_json = json.loads(applications_response)
            applicatons_content = applications_json['content'][0]
            applications_layertree = applicatons_content['layerTree']
            print('Applications', applications_json)
            self.layer_ids = self.find_all_layer_ids(applications_layertree)

            # request (all public) layers
            layers_response = self.request_public_entity(layers_url)
            layers_josn = json.loads(layers_response)
            layers_content = layers_josn['content']

            # get specific layers
            result = [layer for layer in layers_content if layer["id"] == self.layer_ids[0]]
            print('Layer', result)
