# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QgisShogunEditor
                                 A QGIS plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-09
        git sha              : $Format:%H$
        copyright            : (C) 2025 by terrestris
        email                : info@terrestris.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import json
import os.path

from qgis.core import (
    Qgis,
    QgsBrowserModel,
    QgsCoordinateReferenceSystem,
    QgsMessageLog,
    QgsNetworkAccessManager,
    QgsPointXY,
    QgsProject,
    QgsRectangle,
    QgsSettings,
)

# some things for doing http requests
from qgis.PyQt.QtCore import QCoreApplication, QEventLoop, QSettings, Qt, QTranslator, QUrl
from qgis.PyQt.QtGui import QDesktopServices, QIcon, QPixmap
from qgis.PyQt.QtNetwork import QNetworkRequest, QSslSocket
from qgis.PyQt.QtWidgets import QAction

from .models.Application import Application
from .qgis_shogun_editor_dialog import QgisShogunEditorDialog
from .service.Application import ApplicationService
from .service.GraphQLClient import GraphQLClient
from .service.LayerService import LayerService


class QgisShogunEditor:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.layer_service = None
        self.app_service = None
        self.graphql_client = None
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # TODO initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'qgis_shogun_editor{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Shogun Qgis Configurator')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        # self.first_start = None

        # read all settings from qgis settings
        self.settings = QgsSettings()

        # read actual browser model
        self.browser_model = QgsBrowserModel()

        # network access
        self.na_manager = QgsNetworkAccessManager.instance()
        self.request = QNetworkRequest()

        # Achtung: T/F bei Zertifikaten
        self.disable_ssl_verification = self.settings.value(
            "/MetaSearch/disableSSL",
            True,
            bool
        )

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ShogunQgisConfigurator', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToWebMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        icon_path = os.path.join(os.path.dirname(__file__), "shogun_logo.png")
        self.add_action(
            icon_path,
            text=self.tr(u'Shogun Qgis Configurator'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginWebMenu(
                self.tr(u'Shogun Qgis Configurator'),
                action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start:
            self.first_start = False
            self.dlg = QgisShogunEditorDialog()

            self.dlg.entryUrl.setPlaceholderText('Please enter an URL')

            self.dlg.loadButton.clicked.connect(lambda: self.initialize_graphql_and_load_app_list())

            self.dlg.applicationsList.itemDoubleClicked.connect(self._handle_double_click)

            # add logo
            logo_path = os.path.join(os.path.dirname(__file__), "shogun_logo.png")
            if logo_path:
                # build
                pixmap = QPixmap(logo_path)
                # draw preview
                self.dlg.labelLogo.setPixmap(pixmap.scaled(self.dlg.labelLogo.size(),
                                             Qt.KeepAspectRatio, Qt.SmoothTransformation))
                self.dlg.labelLogo.mousePressEvent = self.open_project_link
            else:
                QgsMessageLog.logMessage("An error occured while try to open url: ", 'QgisShogunEditor',
                                         level=Qgis.Critical)
            # add link to github for help
            # help_icon_path = os.path.join(os.path.dirname(__file__), "questionmark.png")
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    def _handle_double_click(self, item):
        QgsMessageLog.logMessage(
            f"You selected: {item.text()} - application id is: {item.application_id}", 'QgisShogunEditor',
            level=Qgis.Info
        )
        QgsProject.instance().setTitle(item.text())
        application = self.app_service.get_application_by_id(item.application_id)
        self.apply_mapview(application)
        if application is not None:
            if application.layer_tree is not None:
                try:
                    QgsMessageLog.logMessage(
                        f"Found layer tree {application.layer_tree}:",
                        'QgisShogunEditor',
                        level=Qgis.Info
                    )
                except json.JSONDecodeError as e:
                    QgsMessageLog.logMessage(
                        f"Could not decode layer tree json: {e}", 'QgisShogunEditor',
                        level=Qgis.Critical
                    )
            else:
                QgsMessageLog.logMessage("Application has no layer tree", 'QgisShogunEditor', level=Qgis.Warning)

    def apply_mapview(self, application: Application):
        qgis_project = QgsProject.instance()
        client_config = application.client_config
        if client_config is not None and 'mapView' in client_config:
            map_view = client_config.get('mapView')
            projection = map_view.get('projection')
            center = map_view.get('center')
            crs = QgsCoordinateReferenceSystem(projection)
            qgis_project.setCrs(crs)

            map_canvas = self.iface.mapCanvas()
            map_canvas.setCenter(QgsPointXY(center[0], center[1]))

            zoom = map_view.get('zoom')
            resolutions = map_view.get('resolutions')
            if resolutions is not None and zoom is not None and zoom < len(resolutions):
                resolution = resolutions[zoom]
                dpi = 25.4 / 0.28
                inches_per_meter = 39.37
                map_canvas.zoomScale(resolution * dpi * inches_per_meter)

    def open_project_link(self, event):
        if event.button() == Qt.LeftButton:
            QDesktopServices.openUrl(QUrl("https://www.terrestris.de/de/"))

    def request_public_entity(self, url):
        self.request.setUrl(QUrl(url))

        # no certificate
        ssl_config = self.request.sslConfiguration()
        ssl_config.setPeerVerifyMode(QSslSocket.VerifyNone)
        self.request.setSslConfiguration(ssl_config)

        # request public application
        self.reply = self.na_manager.get(self.request)
        event_loop = QEventLoop()
        self.reply.finished.connect(event_loop.quit)
        event_loop.exec_()  # blocs until finished

        if self.reply.error() == self.reply.NoError:
            self.response = self.reply.readAll().data().decode("utf-8")
            # print("Response:", self.response)
        else:
            self.response = None
            print("Error:", self.reply.errorString())
        self.reply.deleteLater()

        return self.response

    def find_all_layer_ids(self, layer_tree_json):
        layer_ids = []

        if "layerId" in layer_tree_json:
            print('Found layerId', layer_tree_json["layerId"])
            layer_ids.append(layer_tree_json["layerId"])

        if "children" in layer_tree_json:
            for child in layer_tree_json["children"]:
                layer_ids.extend(self.find_all_layer_ids(child))

        return layer_ids

    def sanitize_shogun_url(self, shogun_url):
        if shogun_url.endswith('/graphql'):
            return shogun_url
        elif shogun_url.endswith('/'):
            shogun_url += 'graphql'
            return shogun_url
        else:
            shogun_url += '/graphql'
            return shogun_url

    def initialize_graphql_client(self):
        sanitized_url = self.sanitize_shogun_url(self.dlg.entryUrl.text().strip())
        self.graphql_client = GraphQLClient(sanitized_url)
        self.app_service = ApplicationService(self.graphql_client)
        self.layer_service = LayerService(self.graphql_client)

    # Example usage in your code
    def initialize_graphql_and_load_app_list(self):
        self.initialize_graphql_client()
        applications = self.app_service.get_all_applications_simple()
        if applications is not None:
            self.dlg.applicationsList.clear()
            for app in applications:
                self.dlg.applicationsList.addItem(app.get_qt_list_item())
