# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QgisShogunEditor
                                  A QGIS plugin
  Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                               -------------------
        begin                : 2025-09
        git sha              : $Format:%H$
        copyright            : (C) 2025 by terrestris
        email                : info@terrestris.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Dict, List, Optional

from PyQt5.QtWidgets import QListWidgetItem

from ..models.BaseEntity import BaseEntity


@dataclass
class Application(BaseEntity):
    name: Optional[str] = None
    state_only: Optional[bool] = None
    client_config: Optional[Dict[str, Any]] = None
    layer_tree: Optional[Dict[str, Any]] = None
    layer_config: Optional[Dict[str, Any]] = None
    tool_config: Optional[Dict[str, Any]] = None

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Application':
        base = super().from_dict(data)
        return cls(
            _id=base._id,
            created=base.created,
            modified=base.modified,
            name=data.get('name'),
            state_only=data.get('stateOnly'),
            client_config=data.get('clientConfig'),
            layer_tree=data.get('layerTree'),
            layer_config=data.get('layerConfig'),
            tool_config=data.get('toolConfig')
        )

    def get_qt_list_item(self):
        item = QListWidgetItem(self.name or "Unnamed Application")
        item.application_id = self._id
        return item

    @staticmethod
    def format_date(dt: Optional[datetime]) -> str:
        if dt is None:
            return "-"
        return dt.strftime("%d.%m.%Y")

    def get_created_formatted(self) -> str:
        return self.format_date(self.created)

    def get_modified_formatted(self) -> str:
        return self.format_date(self.modified)

    def get_layer_count(self) -> int:
        if self.layer_tree is None:
            return 0
        return self._count_layers_in_tree(self.layer_tree)

    def _count_layers_in_tree(self, tree: Dict[str, Any]) -> int:
        count = 0
        if "layerId" in tree:
            count += 1
        if "children" in tree:
            for child in tree["children"]:
                count += self._count_layers_in_tree(child)
        return count

    def to_table_row(self) -> List[Any]:
        return [
            self.name or "Unnamed Application",
            self.get_created_formatted(),
            self.get_modified_formatted(),
            self.get_layer_count()
        ]
