# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QgisShogunEditor
                                 A QGIS plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-09
        git sha              : $Format:%H$
        copyright            : (C) 2025 by terrestris
        email                : info@terrestris.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from dataclasses import dataclass
from typing import Any, Dict, Optional

from .BaseEntity import BaseEntity


@dataclass
class Layer(BaseEntity):
    name: Optional[str] = None
    client_config: Optional[Dict[str, Any]] = None
    source_config: Optional[Dict[str, Any]] = None
    features: Optional[Dict[str, Any]] = None
    layerType: Optional[str] = None

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Layer':
        base = super().from_dict(data)
        return cls(
            _id=base._id,
            created=base.created,
            modified=base.modified,
            name=data.get('name'),
            client_config=data.get('clientConfig'),
            source_config=data.get('sourceConfig'),
            features=data.get('features'),
            layerType=data.get('type')
        )
