# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QgisShogunEditor
                                 A QGIS plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-09
        git sha              : $Format:%H$
        copyright            : (C) 2025 by terrestris
        email                : info@terrestris.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from dataclasses import dataclass
from typing import Any, Dict, Optional


@dataclass
class MutateLayer:
    name: str
    _type: str
    client_config: Optional[Dict[str, Any]] = None
    source_config: Optional[Dict[str, Any]] = None
    features: Optional[Dict[str, Any]] = None

    def to_dict(self) -> Dict[str, Any]:
        data = {"name": self.name, "type": self._type}
        if self.client_config is not None:
            data["clientConfig"] = self.client_config
        if self.source_config is not None:
            data["sourceConfig"] = self.source_config
        if self.features is not None:
            data["features"] = self.features
        return data
