# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QgisShogunEditor
                                  A QGIS plugin
  Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                               -------------------
        begin                : 2025-09
        git sha              : $Format:%H$
        copyright            : (C) 2025 by terrestris
        email                : info@terrestris.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import json
from typing import TYPE_CHECKING, Any, Dict, Optional

import requests

from ..exception.GraphQLException import GraphQLException

if TYPE_CHECKING:
    from .KeycloakAuth import KeycloakAuth


class GraphQLClient:
    def __init__(
        self,
        endpoint_url: str,
        headers: Optional[Dict[str, str]] = None,
        keycloak_auth: Optional['KeycloakAuth'] = None
    ):
        self.endpoint_url = endpoint_url
        self.headers = headers or {}
        self._keycloak_auth = keycloak_auth
        self.session = requests.Session()

        self.session.headers.update({
            'Content-Type': 'application/json',
            **self.headers
        })

    def set_keycloak_auth(self, auth: 'KeycloakAuth') -> None:
        self._keycloak_auth = auth

    def _get_auth_headers(self) -> Dict[str, str]:
        if self._keycloak_auth:
            return self._keycloak_auth.get_auth_header()
        return {}

    def execute_query(self, query: str, variables: Optional[Dict] = None) -> Dict[str, Any]:
        payload = {
            'query': query,
            'variables': variables or {}
        }

        auth_headers = self._get_auth_headers()

        try:
            response = self.session.post(
                self.endpoint_url,
                json=payload,
                headers=auth_headers,
                timeout=30
            )
            response.raise_for_status()

            data = response.json()
            if 'errors' in data:
                raise GraphQLException(f"GraphQL errors: {data['errors']}")

            return data.get('data', {})
        except requests.exceptions.RequestException as e:
            raise GraphQLException(f"Network error: {str(e)}")
        except json.JSONDecodeError as e:
            raise GraphQLException(f"JSON decode error: {str(e)}")
